NationalUnion.Web/Controllers/ManagerAccountController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using NationalUnion.Application.Commons;
using NationalUnion.Application.Interfaces;
using NationalUnion.Application.ViewModels;
using NationalUnion.Repository.Interfaces;
using NationalUnion.Web.Commons;

namespace NationalUnion.Web.Controllers
{
    public class ManagerAccountController : Controller
    {
        [Dependency]
        public IManagerAccountBll ManagerAccountBll { get; set; }
        [Dependency]
        public IRegionProvinceCityRepository RegionProvinceCityRepository { get; set; }
        [Dependency]
        public IChannelManageRepository ChannelManageRepository { get; set; }

        // 异常集合
        ValidationErrors _errors = new ValidationErrors();

        public ActionResult ManagerList()
        {
            var typeSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道类型", Value = "-1", Selected = true}
            };
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var rankSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道等级", Value = "-1", Selected = true}
            };
            rankSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Rank"] = rankSelectItems;

            var statusSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道状态", Value = "-1", Selected = true}
            };
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            return View();
        }

        [HttpPost]
        public JsonResult GetManagerList(GridPager pager)
        {
            var list = ManagerAccountBll.GetManagerList(ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ManagerAccount
                    {
                        ManagerId = row.ManagerId,
                        ManagerName = row.ManagerName,
                        ManagerEmail = row.ManagerEmail,
                        MobilePhone = row.MobilePhone,
                        ChannelTypeDesc = EnumHelper.GetDescription((ChannelType)(row.ChannelType)),
                        ChannelName = row.ChannelName,
                        ChannelRankDesc = EnumHelper.GetDescription((ChannelRank)(row.ChannelRank)),
                        ParentId = row.ParentId,
                        ParentChannel = row.ParentId == 0 ? "" : ChannelManageRepository.GetChannelById(row.ParentId).ChannelName,
                        City = row.City,
                        Province = RegionProvinceCityRepository.GetProvinceById(row.ProvinceId).Name,
                        CreatedTime = row.CreatedTime,
                        ModifiedTime = row.ModifiedTime,
                        IsActive = row.IsActive,
                        IsActiveDesc = EnumHelper.GetDescription((Status)(row.IsActive))
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult GetListByQuery(string queryStr, GridPager pager)
        {
            var list = ManagerAccountBll.GetManagerListByQuery(queryStr, ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ManagerAccount
                    {
                        ManagerId = row.ManagerId,
                        ManagerName = row.ManagerName,
                        ManagerEmail = row.ManagerEmail,
                        MobilePhone = row.MobilePhone,
                        ChannelTypeDesc = EnumHelper.GetDescription((ChannelType) (row.ChannelType)),
                        ChannelName = row.ChannelName,
                        ChannelRankDesc = EnumHelper.GetDescription((ChannelRank) (row.ChannelRank)),
                        ParentId = row.ParentId,
                        ParentChannel = row.ParentId == 0 ? "" : ChannelManageRepository.GetChannelById(row.ParentId).ChannelName,
                        City = row.City,
                        Province = RegionProvinceCityRepository.GetProvinceById(row.ProvinceId).Name,
                        CreatedTime = row.CreatedTime,
                        ModifiedTime = row.ModifiedTime,
                        IsActive = row.IsActive,
                        IsActiveDesc = EnumHelper.GetDescription((Status) (row.IsActive))
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult AddManager()
        {
            var typeSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var statusSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            var provinceList = RegionProvinceCityRepository.GetProvinceList();
            var provSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            provSelectItems.AddRange(from prov in provinceList
                select new SelectListItem
                {
                    Text = prov.Name,
                    Value = prov.PId.ToString(CultureInfo.InvariantCulture),
                    Selected = false
                });

            ViewData["ProvList"] = provSelectItems;

            var cityList = RegionProvinceCityRepository.GetCityListByProvId(0);
            var citySelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            citySelectItems.AddRange(from city in cityList
                select new SelectListItem
                {
                    Text = city.Name,
                    Value = city.CId.ToString(CultureInfo.InvariantCulture),
                    Selected = false
                });

            ViewData["CityList"] = citySelectItems;

            return View();
        }

        [HttpPost]
        public JsonResult AddManager(ManagerAccount model)
        {
            if (ManagerAccountBll.AddManager(model, ref _errors))
            {
                return new ToJsonResult
                {
                    Data = 1,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            return new ToJsonResult
            {
                Data = 0,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult EditManager(Int64 managerId)
        {
            ManagerAccount entity = ManagerAccountBll.GetManagerById(managerId);

            var typeSelectItems = new List<SelectListItem>();
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var statusSelectItems = new List<SelectListItem>();
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            var provinceList = RegionProvinceCityRepository.GetProvinceList();
            var provSelectItems = new List<SelectListItem>();

NationalUnion.Web/Views/Home/AccountEdit.cshtml
@using System.Web.UI.WebControls
@using NationalUnion.Domain.Mapping
@model NationalUnion.Application.ViewModels.ManagerAccount
@{
    ViewBag.Title = "AccountEdit";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

<div class="mvctool bgb">
    <a id="btnSave" style="float: left;" class="l-btn l-btn-plain">
        <span class="l-btn-left"><span class="l-btn-text icon-save" style="padding-left: 20px;">保存</span></span>
    </a>
</div>
@using (Html.BeginForm("AccountEdit", "Home", null, FormMethod.Post, new { Id = "AccountEditForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerId, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerId)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerName, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelTypeStr)：
                </td>
                <td>
                    @Html.DropDownList("ChannelTypeStr", (List<SelectListItem>)ViewData["ChannelType"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelName, new { style = "width: 200px;" })
                    @Html.Hidden("ChannelId")
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerEmail)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerEmail, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerEmail)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.MobilePhone)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.MobilePhone, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.MobilePhone)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ProvinceId)：
                </td>
                <td>
                    @Html.DropDownList("ProvinceId", (List<SelectListItem>)ViewData["ProvList"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CityId)：
                </td>
                <td>
                    @Html.DropDownList("CityId", (List<SelectListItem>)ViewData["CityList"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IsActiveStr)：
                </td>
                <td>
                    @Html.DropDownList("IsActiveStr", (List<SelectListItem>)ViewData["Status"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
        </tbody>
    </table>
}

<script type="text/javascript">
    $(document).ready(function() {
        $("#ChannelName").autocomplete({
            source:function(request, response) {
                $.ajax({
                    url: "@Url.Action("Search","Home")",
                    type: "POST",
                    dataType: "json",   // json格式数据，默认是text
                    //data: { keyword: request.term },  // 参数
                    data: { channelType: $("#ChannelTypeStr").val(), keyword: $("#ChannelName").val() }, // 参数
                    success:function(data) {
                        response($.map(data, function(item) {
                            return { label: item.text, value: item.value }; // 将返回的jsonresult的属性赋值给autocomplete item
                        }));
                    }
                });
            },
            focus:function(event, ui) {
                $("#ChannelName").val(ui.item.label);   // 选中item的文本
                return false;
            },
            select:function(event, ui) {
                $("#ChannelName").val(ui.item.label);   // 选中item的文本
                $('#ChannelId').val(parseInt(ui.item.value));    // 选中item的值
                return false;
            }
        });
    });
</script>

@{
    var channelst = ViewData["ChannelList"];
}
<script type="text/javascript">
    @*var channelst = '@channelst';
    var chan = [
        "人文学院/1",
        "外语学院/2",
        "计算机学院/3",
        "通信学院/4",
        "信息技术学院/5",
        "第一临床医学院/6",
        "第二临床医学院/7",
        "经贸学院/8",
        "财经学院/9",
        "中文学院/10",
        "公共管理学院/11",
        "语言学院/12"
    ];

    $("#ChannelName").autocomplete({
        source: channelst
    });
    $("#ChannelName").autocomplete({
        source: chan
    });*@

    // 页面加载时初始化下拉框
    $("#ChannelTypeStr option[value='@Model.ChannelTypeStr']").attr("selected", true);
    $("#IsActiveStr option[value='@Model.IsActiveStr']").attr("selected", true);
    // 下拉框默认选中
    $("#ProvinceId option[value='@Model.ProvinceId']").attr("selected", true);
    $("#CityId option[value='@Model.CityId']").attr("selected", true);

    $(function () {
        $("#ProvinceId").change(function () {
            //var proVal = $("select[name='ProvinceId'] option[selected]").val();
            //$("#ProvinceStr").val(proVal);
            changeCity();
        });
    });

    // 根据省份加载城市
    function changeCity() {
        var selectedProvinceId = $("#ProvinceId").val();
        //$("#ProvinceStr").val(selectedProvinceId);
        if (selectedProvinceId.length == 0) {
            emptyCity();
        } else {
            $.post('@Url.Action("GetCityList", "Home")', { pid: parseInt(selectedProvinceId) }, function (data) {
                $('#CityId').empty();
                $.each(data, function (i, item) {
                    $('#CityId').append($('<option></option>').val(item.Value).text(item.Text));
                });
            });
        }
    }

    // 设置城市清空
    function emptyCity() {
        $('#CityId').empty();
        $('#CityId').append($('<option></option>').val('').text('请选择'));
    }

    //$("#CityId").change(function () {
    //    var cityVal = $("#CityId").val();
    //    $("#CityStr").val(cityVal);
    //});
</script>

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            $.ajax({
                url: "/Home/AccountEdit",
                type: "POST",
                data: $("#AccountEditForm").serialize(),
                dataType: "json",
                success: function (data) {
                    if (data == 1) {
                        window.parent.frameReturnByMes("成功");
                        window.parent.frameReturnByClose();
                    } else {
                        window.parent.frameReturnByMes("失败");
                    }
                }
            });
        });
    });
</script>

NationalUnion.Web/Views/Home/AccountPerfect.cshtml
@using System.Web.Mvc.Html
@using NationalUnion.Application.Commons
@model NationalUnion.Application.ViewModels.ManagerAccount
@{
    ViewBag.Title = "AccountPerfect";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";

    if (Request.Cookies["memberNo"] != null)
    {
        var memberNoCookie = Request.Cookies["memberNo"].Value;
        var memberNo = Int64.Parse(memberNoCookie);
    }
}

<script src="/Scripts/jquery.min.js" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
@Styles.Render("~/Content/themes/bootstrap/css")
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />
<style type="text/css">
    .btn {
        display: inline-block;
        color: #FFF;
        background: url("/Content/images/btn_bg.png") repeat-x;
        line-height: 1;
        border-radius: 3px;
        vertical-align: middle;
    }

    .btn-text {
        vertical-align: top;
        text-align: center;
        height: 26px;
        line-height: 25px;
        padding: 0 12px;
        border: 1px solid #999;
        border-radius: 3px;
        cursor: pointer;
    }

    #btnCancel {
        margin-top: 20px;
        margin-left: 135px;
    }

    #btnSave {
        margin-top: 20px;
        margin-left: 20px;
    }
</style>

@*<div class="mvctool bgb">
    <a id="btnSave" style="float: left;" class="l-btn l-btn-plain">
        <span class="l-btn-left"><span class="l-btn-text icon-save" style="padding-left: 20px;">保存</span></span>
    </a>
</div>*@
@using (Html.BeginForm("AccountPerfect", "Home", null, FormMethod.Post, new { Id = "AccountPerfectForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerId, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerId)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerName, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerEmail)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerEmail, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ManagerEmail)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.MobilePhone)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.MobilePhone, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.MobilePhone)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IdCardNo)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.IdCardNo, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.IdCardNo)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelTypeStr)：
                </td>
                <td>
                    @Html.DropDownList("ChannelTypeStr", (List<SelectListItem>)ViewData["ChannelType"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr id="Channel">
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelName, new { style = "width: 200px;" })
                    @Html.Hidden("ChannelId")
                </td>
                <td>
                    @Html.Label("输入渠道包含信息如*北京*", new { style = "color: red;" })
                </td>
            </tr>
            <tr id="ShareChannel">
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ShareChannelName)：
                </td>
                <td>
                    @Html.DropDownList("ShareChannelName", (List<SelectListItem>)ViewData["ShareChannel"], new { style = "width: 208px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ProvinceId)：
                </td>
                <td>
                    @Html.DropDownList("ProvinceId", (List<SelectListItem>)ViewData["ProvList"], new { style = "width:208px; height:22px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CityId)：
                </td>
                <td>
                    @Html.DropDownList("CityId", (List<SelectListItem>)ViewData["CityList"], new { style = "width:208px; height:22px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IsActiveStr)：
                </td>
                <td>
                    @Html.DropDownList("IsActiveStr", (List<SelectListItem>)ViewData["Status"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
        </tbody>
    </table>
}
<div>
    <a id="btnCancel"><span class="btn btn-text">取 消</span></a>
    <a id="btnSave"><span class="btn btn-text">提 交</span></a>
</div>
<div id="mes" class="field-validation-error"></div>

<script type="text/javascript">
    $(document).ready(function () {
        var selectValue = $("#ChannelTypeStr").val();
        checkBySelectedType(selectValue);
    });

    $("#ChannelTypeStr").change(function () {
        var selectValue = $("select[name='ChannelTypeStr']").val();
        checkBySelectedType(selectValue);
    });

    var checkBySelectedType = function (value) {
        if (value == '@((ChannelType.ShareTool).ToString())') {
            $("#Channel").hide();
            $("#ShareChannel").show();
        } else {
            $("#Channel").show();
            $("#ShareChannel").hide();
        }
    };
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ChannelName").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "@Url.Action("Search", "ManagerAccount")",
                    type: "POST",
                    dataType: "json",   // json格式数据，默认是text
                    //data: { keyword: request.term },  // 参数
                    data: { channelType: $("#ChannelTypeStr").val(), keyword: $("#ChannelName").val() }, // 参数
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.text, value: item.value }; // 将返回的jsonresult的属性赋值给autocomplete item
                        }));
                    }
                });
            },
            focus: function (event, ui) {
                $("#ChannelName").val(ui.item.label);   // 选中item的文本
                return false;
            },
            select: function (event, ui) {
                $("#ChannelName").val(ui.item.label);   // 选中item的文本
                $('#ChannelId').val(parseInt(ui.item.value));    // 选中item的值
                return false;
            }
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        $("#ProvinceId").change(function () {
            changeCity();
        });
    });

    // 根据省份加载城市
    function changeCity() {
        var selectedProvinceId = $("#ProvinceId").val();
        if (selectedProvinceId.length == 0) {
            emptyCity();
        } else {
            $.post('@Url.Action("GetCityList", "ManagerAccount")', { pid: parseInt(selectedProvinceId) }, function (data) {
                $('#CityId').empty();
                $.each(data, function (i, item) {
                    $('#CityId').append($('<option></option>').val(item.Value).text(item.Text));
                });
            });
        }
    }

    // 设置城市清空
    function emptyCity() {
        $('#CityId').empty();
        $('#CityId').append($('<option></option>').val('').text('请选择'));
    }
</script>

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            $.ajax({
                url: "/Home/AccountPerfect",
                type: "POST",
                data: $("#AccountPerfectForm").serialize(),
                dataType: "json",
                success: function (data) {
                    if (data.Type == 1) {
                        window.parent.frameReturnByClose();
                    } else {
                        $("#mes").html(data.Message);
                    }
                }
            });
        });
    });
</script>