NationalUnion.Web/Controllers/ChannelManageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using NationalUnion.Application.Commons;
using NationalUnion.Application.Interfaces;
using NationalUnion.Application.ViewModels;
using NationalUnion.Repository.Interfaces;
using NationalUnion.Web.Commons;

namespace NationalUnion.Web.Controllers
{
    public class ChannelManageController : Controller
    {
        [Dependency]
        public IChannelManageBll ChannelManageBll { get; set; }
        [Dependency]
        public IChannelManageRepository ChannelManageRepository { get; set; }

        public ActionResult ChannelList()
        {
            var typeSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道类型", Value = "-1", Selected = true}
            };
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var rankSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道等级", Value = "-1", Selected = true}
            };
            rankSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Rank"] = rankSelectItems;

            var statusSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道状态", Value = "-1", Selected = true}
            };
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            return View();
        }

        public JsonResult GetChannelList(GridPager pager)
        {
            var list = ChannelManageBll.GetChannelList(ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ChannelInfo
                    {
                        ChannelId = row.ChannelId,
                        ChannelName = row.ChannelName,
                        RankDesc = EnumHelper.GetDescription((ChannelRank)(row.Rank)),
                        ChannelTypeDesc = EnumHelper.GetDescription((ChannelType)(row.ChannelType)),
                        ParentId = row.ParentId,
                        ParentChannel = row.ParentId == 0 ? "" : ChannelManageBll.GetChannelById(row.ParentId).ChannelName,
                        KeyWord = row.KeyWord,
                        CreatedTime = row.CreatedTime,
                        ModifiedTime = row.ModifiedTime,
                        IsActive = row.IsActive,
                        IsActiveDesc = EnumHelper.GetDescription((Status)(row.IsActive))
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult GetListByQuery(string queryStr, GridPager pager)
        {
            var list = ChannelManageBll.GetChannelListByQuery(queryStr, ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ChannelInfo
                    {
                        ChannelId = row.ChannelId,
                        ChannelName = row.ChannelName,
                        RankDesc = EnumHelper.GetDescription((ChannelRank)(row.Rank)),
                        ChannelTypeDesc = EnumHelper.GetDescription((ChannelType)(row.ChannelType)),
                        ParentId = row.ParentId,
                        ParentChannel = row.ParentId == 0 ? "" : ChannelManageBll.GetChannelById(row.ParentId).ChannelName,
                        KeyWord = row.KeyWord,
                        CreatedTime = row.CreatedTime,
                        ModifiedTime = row.ModifiedTime,
                        IsActive = row.IsActive,
                        IsActiveDesc = EnumHelper.GetDescription((Status)(row.IsActive))
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult AddChannel()
        {
            var typeSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var rankSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            rankSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Rank"] = rankSelectItems;

            var statusSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "请选择", Value = "-1", Selected = true}
            };
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            return View();
        }

        [HttpPost]
        public ActionResult Search(string channelType, string keyword)
        {
            var items = new List<object>();
            var channelList = ChannelManageRepository.GetChannelList();
            if (!channelType.Equals("-1"))
            {
                int type = Convert.ToInt32(Enum.Parse(typeof (ChannelType), channelType));
                channelList = channelList.Where(c => c.ChannelType == type);
            }
            var channelNameIdList = channelList.ToList().Where(c => c.ChannelName.Contains(keyword));
            items.AddRange(channelNameIdList.Select(c => new
            {
                text = c.ChannelName + "/" + c.ChannelId,
                value = c.ChannelId.ToString(CultureInfo.InvariantCulture)
            }));

            return Json(items, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddChannel(ChannelInfo model)
        {
            if (ChannelManageBll.AddChannel(model))
            {
                return new ToJsonResult
                {
                    Data = 1,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            return new ToJsonResult
            {
                Data = 0,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult EditChannel(int channelId)
        {
            ChannelInfo entity = ChannelManageBll.GetChannelById(channelId);

            var typeSelectItems = new List<SelectListItem>();
            typeSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelType))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelType) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelType"] = typeSelectItems;

            var rankSelectItems = new List<SelectListItem>();
            rankSelectItems.AddRange(from object value in Enum.GetValues(typeof (ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Rank"] = rankSelectItems;

            var statusSelectItems = new List<SelectListItem>();
            statusSelectItems.AddRange(from object value in Enum.GetValues(typeof (Status))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((Status) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["Status"] = statusSelectItems;

            entity.ParentChannel = ChannelManageBll.GetChannelById(entity.ParentId).ChannelName;
            entity.RankStr = Enum.Parse(typeof(ChannelRank), (entity.Rank).ToString(CultureInfo.InvariantCulture)).ToString();

NationalUnion.Web/Views/ChannelManage/AddChannel.cshtml
@model NationalUnion.Application.ViewModels.ChannelInfo
@{
    ViewBag.Title = "AddChannel";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

<div class="mvctool bgb">
    <a id="btnSave" style="float: left;" class="l-btn l-btn-plain">
        <span class="l-btn-left"><span class="l-btn-text icon-save" style="padding-left: 20px;">保存</span></span>
    </a>
</div>
@using (Html.BeginForm("AddChannel", "ChannelManage", null, FormMethod.Post, new { Id = "AddChannelForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelName, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelTypeStr)：
                </td>
                <td>
                    @Html.DropDownList("ChannelTypeStr", (List<SelectListItem>)ViewData["ChannelType"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.RankStr)：
                </td>
                <td>
                    @Html.DropDownList("RankStr", (List<SelectListItem>)ViewData["Rank"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ParentChannel)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ParentChannel, new { style = "width: 200px;" })
                    @Html.Hidden("ParentId")
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ParentChannel)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.KeyWord)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.KeyWord, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.KeyWord)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IsActiveStr)：
                </td>
                <td>
                    @Html.DropDownList("IsActiveStr", (List<SelectListItem>)ViewData["Status"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
        </tbody>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#ParentChannel").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "@Url.Action("Search", "ChannelManage")",
                    type: "POST",
                    dataType: "json",   // json格式数据，默认是text
                    //data: { keyword: request.term },  // 参数
                    data: { channelType:$("#ChannelTypeStr").val(), keyword: $("#ParentChannel").val() }, // 参数
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.text, value: item.value }; // 将返回的jsonresult的属性赋值给autocomplete item
                        }));
                    }
                });
            },
            focus: function (event, ui) {
                $("#ParentChannel").val(ui.item.label);   // 选中item的文本
                return false;
            },
            select: function (event, ui) {
                $("#ParentChannel").val(ui.item.label);   // 选中item的文本
                $('#ParentId').val(parseInt(ui.item.value));    // 选中item的值
                return false;
            }
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            $.ajax({
                url: "/ChannelManage/AddChannel",
                type: "POST",
                data: $("#AddChannelForm").serialize(),
                datatype: "json",
                success: function (data) {
                    if (data == 1) {
                        window.parent.frameReturnByMes("成功");
                        window.parent.frameReturnByReload(true);
                        window.parent.frameReturnByClose();
                    } else {
                        window.parent.frameReturnByMes("失败");
                    }
                }
            });
        });
    })
</script>

NationalUnion.Web/Views/ChannelManage/DetailChannel.cshtml
@model NationalUnion.Application.ViewModels.ChannelInfo
@{
    ViewBag.Title = "DetailChannel";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@using (Html.BeginForm("DetailChannel", "ChannelManage", null, FormMethod.Post, new { Id = "DetailChannelForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelId, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelId)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelName, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelTypeStr)：
                </td>
                <td>
                    @Html.DropDownList("ChannelTypeStr", (List<SelectListItem>)ViewData["ChannelType"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.RankStr)：
                </td>
                <td>
                    @Html.DropDownList("RankStr", (List<SelectListItem>)ViewData["Rank"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ParentChannel)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ParentChannel, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ParentChannel)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.KeyWord)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.KeyWord, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.KeyWord)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CreatedTime)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.CreatedTime, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.CreatedTime)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ModifiedTime)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ModifiedTime, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ModifiedTime)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IsActiveStr)：
                </td>
                <td>
                    @Html.DropDownList("IsActiveStr", (List<SelectListItem>)ViewData["Status"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
        </tbody>
    </table>
}

NationalUnion.Web/Views/ChannelManage/EditChannel.cshtml
@model NationalUnion.Application.ViewModels.ChannelInfo
@{
    ViewBag.Title = "EditChannel";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
<link href="~/Content/jquery-ui.css" rel="stylesheet" />

<div class="mvctool bgb">
    <a id="btnSave" style="float: left;" class="l-btn l-btn-plain">
        <span class="l-btn-left"><span class="l-btn-text icon-save" style="padding-left: 20px;">保存</span></span>
    </a>
</div>
@using (Html.BeginForm("EditChannel", "ChannelManage", null, FormMethod.Post, new { Id = "EditChannelForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelId, new { style = "width: 200px;", @readonly = true })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelId)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ChannelName, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ChannelName)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ChannelTypeStr)：
                </td>
                <td>
                    @Html.DropDownList("ChannelTypeStr", (List<SelectListItem>)ViewData["ChannelType"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.RankStr)：
                </td>
                <td>
                    @Html.DropDownList("RankStr", (List<SelectListItem>)ViewData["Rank"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ParentChannel)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ParentChannel, new { style = "width: 200px;" })
                    @Html.Hidden("ParentId")
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.ParentChannel)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.KeyWord)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.KeyWord, new { style = "width: 200px;" })
                </td>
                <td>
                    @Html.ValidationMessageFor(model => model.KeyWord)
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.IsActiveStr)：
                </td>
                <td>
                    @Html.DropDownList("IsActiveStr", (List<SelectListItem>)ViewData["Status"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
        </tbody>
    </table>
}

<script type="text/javascript">
    // 页面加载时初始化下拉框
    @*$("select[name='RankStr']").val("@Model.RankStr");
    $("select[name='IsActiveStr']").val("@Model.IsActiveStr");*@
    //debugger;
    $("#ChannelTypeStr option[value='@Model.ChannelTypeStr']").attr("selected", true);
    $("#RankStr option[value='@Model.RankStr']").attr("selected", true);
    $("#IsActiveStr option[value='@Model.IsActiveStr']").attr("selected", true);
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ParentChannel").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "@Url.Action("Search","ChannelManage")",
                    type: "POST",
                    dataType: "json",   // json格式数据，默认是text
                    //data: { keyword: request.term },  // 参数
                    data: { channelType: $("#ChannelTypeStr").val(), keyword: $("#ParentChannel").val() }, // 参数
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.text, value: item.value }; // 将返回的jsonresult的属性赋值给autocomplete item
                        }));
                    }
                });
            },
            focus: function (event, ui) {
                $("#ParentChannel").val(ui.item.label);   // 选中item的文本
                return false;
            },
            select: function (event, ui) {
                $("#ParentChannel").val(ui.item.label);   // 选中item的文本
                $('#ParentId').val(parseInt(ui.item.value));    // 选中item的值
                return false;
            }
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        $("#btnSave").click(function () {
            $.ajax({
                url: "/ChannelManage/EditChannel",
                type: "POST",
                data: $("#EditChannelForm").serialize(),
                datatype: "json",
                success: function (data) {
                    if (data == 1) {
                        window.parent.frameReturnByMes("成功");
                        window.parent.frameReturnByReload(true);
                        window.parent.frameReturnByClose();
                    } else {
                        window.parent.frameReturnByMes("失败");
                    }
                }
            });
        });
    });
</script>