NationalUnion.Web/Controllers/ManagerDetailController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using NationalUnion.Application.Commons;
using NationalUnion.Application.Interfaces;
using NationalUnion.Application.ViewModels;
using NationalUnion.Web.Commons;

namespace NationalUnion.Web.Controllers
{
    public class ManagerDetailController : Controller
    {
        [Dependency]
        public IManagerDetailBll ManagerDetailBll { get; set; }
        [Dependency]
        public IChannelManageBll ChannelManageBll { get; set; }

        public ActionResult ManagerDetailList()
        {
            var currentRankSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "当前渠道等级", Value = "-1", Selected = true}
            };
            currentRankSelectItems.AddRange(from object value in Enum.GetValues(typeof(ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank)(value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["CurrentRank"] = currentRankSelectItems;

            var oldRankSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "历史渠道等级", Value = "-1", Selected = true}
            };
            oldRankSelectItems.AddRange(from object value in Enum.GetValues(typeof(ChannelRank))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["OldRank"] = oldRankSelectItems;

            var rankChangeStatusSelectItems = new List<SelectListItem>
            {
                new SelectListItem {Text = "渠道等级状态", Value = "-1", Selected = true}
            };
            rankChangeStatusSelectItems.AddRange(from object value in Enum.GetValues(typeof(ChannelRankChangeStatus))
                select new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRankChangeStatus)(value)),
                    Value = value.ToString(),
                    Selected = false
                });

            ViewData["ChannelRankChange"] = rankChangeStatusSelectItems;

            return View();
        }

        public JsonResult GetManagerDetailList(GridPager pager)
        {
            var list = ManagerDetailBll.GetManagerDetailList(ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ManagerDetailInfo
                    {
                        ManagerDetailId = row.ManagerDetailId,
                        ManagerId = row.ManagerId,
                        ManagerName = row.ManagerName,
                        CurrentChannelId = row.CurrentChannelId,
                        CurrentChannel = ChannelManageBll.GetChannelById(row.CurrentChannelId).ChannelName,
                        OldChannelId = row.OldChannelId,
                        OldChannel = ChannelManageBll.GetChannelById(row.OldChannelId).ChannelName,
                        CurrentRankDesc = EnumHelper.GetDescription((ChannelRank) (row.CurrentRank)),
                        OldRankDesc = EnumHelper.GetDescription((ChannelRank) (row.OldRank)),
                        RankStatusDesc = EnumHelper.GetDescription((ChannelRankChangeStatus) (row.RankStatus)),
                        CreatedTime = row.CreatedTime
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public JsonResult GetListByQuery(string queryStr, GridPager pager)
        {
            var list = ManagerDetailBll.GetManagerDetailListByQuery(queryStr, ref pager);

            var json = new
            {
                total = pager.TotalRows,
                rows = list.Select(row =>
                    new ManagerDetailInfo
                    {
                        ManagerDetailId = row.ManagerDetailId,
                        ManagerId = row.ManagerId,
                        ManagerName = row.ManagerName,
                        CurrentChannelId = row.CurrentChannelId,
                        OldChannelId = row.OldChannelId,
                        CurrentRankDesc = EnumHelper.GetDescription((ChannelRank) (row.CurrentRank)),
                        OldRankDesc = EnumHelper.GetDescription((ChannelRank) (row.OldRank)),
                        RankStatusDesc = EnumHelper.GetDescription((ChannelRankChangeStatus) (row.RankStatus)),
                        CreatedTime = row.CreatedTime
                    }).ToArray()
            };

            return new ToJsonResult
            {
                Data = json,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult GetManagerDetail(int managerDetailId)
        {
            ManagerDetailInfo entity = ManagerDetailBll.GetManagerDetailById(managerDetailId);
            var currentRankSelectItems = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (entity.CurrentRank)),
                    Value = (entity.CurrentRank).ToString(CultureInfo.InvariantCulture),
                    Selected = true
                }
            };

            ViewData["CurrentRank"] = currentRankSelectItems;

            var oldRankSelectItems = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRank) (entity.OldRank)),
                    Value = (entity.OldRank).ToString(CultureInfo.InvariantCulture),
                    Selected = true
                }
            };

            ViewData["OldRank"] = oldRankSelectItems;

            var rankStatusSelectItems = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = EnumHelper.GetDescription((ChannelRankChangeStatus) (entity.RankStatus)),
                    Value = (entity.RankStatus).ToString(CultureInfo.InvariantCulture),
                    Selected = true
                }
            };

            ViewData["RankStatus"] = rankStatusSelectItems;

            return View(entity);
        }

        [HttpPost]
        public JsonResult DeleteManagerDetail(int managerDetailId)
        {
            if (ManagerDetailBll.DeleteManagerDetail(managerDetailId))
            {
                return new JsonResult
                {
                    Data = 1,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            return new JsonResult
            {
                Data = 0,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

NationalUnion.Web/Views/ManagerDetail/GetManagerDetail.cshtml
@model NationalUnion.Application.ViewModels.ManagerDetailInfo
@{
    ViewBag.Title = "GetManagerDetail";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}

@using (Html.BeginForm("GetManagerDetail", "ManagerDetail", null, FormMethod.Post, new { Id = "GetManagerDetailForm" }))
{
    @Html.ValidationSummary(true);
    <table class="fromEditTable setTextWidth300">
        <tbody>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerDetailId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerDetailId, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerId)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerId, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.ManagerName)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.ManagerName, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CurrentChannel)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.CurrentChannel, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.OldChannel)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.OldChannel, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CurrentRankStr)：
                </td>
                <td>
                    @Html.DropDownList("CurrentRankStr", (List<SelectListItem>)ViewData["CurrentRank"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.OldRankStr)：
                </td>
                <td>
                    @Html.DropDownList("OldRankStr", (List<SelectListItem>)ViewData["OldRank"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.RankStatusStr)：
                </td>
                <td>
                    @Html.DropDownList("RankStatusStr", (List<SelectListItem>)ViewData["RankStatus"], new { style = "width:208px; height:22px;" })
                </td>
            </tr>
            <tr>
                <td style="width: 100px; text-align: right;">
                    @Html.LabelFor(model => model.CreatedTime)：
                </td>
                <td>
                    @Html.TextBoxFor(model => model.CreatedTime, new { style = "width: 200px;", @readonly = true })
                </td>
            </tr>
        </tbody>
    </table>
}

NationalUnion.Web/Views/ManagerDetail/ManagerDetailList.cshtml
@using NationalUnion.Application.Commons
@using NationalUnion.Web.HtmlHelpers
@{
    ViewBag.Title = "ManagerDetailList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="List">
    <div id="modalwindow" class="easyui-window" data-options="modal:true,closed:true,minimizable:false,shadow:false"></div>
    <div class="mvctool">
        <input id="txtQuery" type="text" value="输入*负责人*关键字" onfocus="if(value=='输入*负责人*关键字') {value='';}" onblur="if(value=='') {value='输入*负责人*关键字';}" style="text-align: center;" class="searchText">
        @Html.DropDownList("CurrentRankStr", (List<SelectListItem>)ViewData["CurrentRank"], new { style = "height:22px; float:left; margin: 3px 5px 0 0; width: 120px;" })
        @Html.DropDownList("OldRankStr", (List<SelectListItem>)ViewData["OldRank"], new { style = "height:22px; float:left; margin: 3px 5px 0 0; width: 120px;" })
        @Html.DropDownList("ChannelRankChangeStr", (List<SelectListItem>)ViewData["ChannelRankChange"], new { style = "height:22px; float:left; margin: 3px 5px 0 0; width: 120px;" })
        @Html.ToolButton("btnQuery", "icon-search", "查询", true)
        @Html.ToolButton("btnDetails", "icon-details", "详细", true)
        @Html.ToolButton("btnDelete", "icon-remove", "删除", true)
    </div>
</table>

<script type="text/javascript">
    $(function () {
        $('#List').datagrid({
            url: '/ManagerDetail/GetManagerDetailList',
            width: $(window).width() - 10,
            method: 'post',
            height: $(window).height() - 40,
            fitColumns: true,
            sortName: 'ManagerDetailId',
            sortOrder: 'desc',
            idField: 'ManagerDetailId',
            pageSize: 10,
            pageList: [10, 20, 30, 40, 50],
            pagination: true,
            striped: true,
            singleSelect: true,
            rownumbers: true,
            columns: [
                [
                    { field: 'ManagerDetailId', title: '历史明细编号', width: 40 },
                    { field: 'ManagerId', title: '会员编号', width: 40 },
                    { field: 'ManagerName', title: '会员姓名', width: 40 },
                    { field: 'CurrentChannel', title: '当前渠道', width: 40 },
                    { field: 'CurrentRankDesc', title: '当前渠道等级', width: 40, align: 'center' },
                    { field: 'OldChannel', title: '历史渠道', width: 40, align:'center' },
                    { field: 'OldRankDesc', title: '历史渠道等级', width: 40, align: 'center' },
                    { field: 'RankStatusDesc', title: '渠道等级状态', width: 40, align: 'center' },
                    { field: 'CreatedTime', title: '记录创建时间', width: 80, align: 'center' }
                ]
            ]
        });
    });
</script>

<script type="text/javascript">
    // 自动DataGrid，从第一次加载与重置窗体大小时候发生的事件：分部视图
    $(function () {
        $(window).resize(function () {
            $('#List').datagrid('resize', {
                width: $(window).width() - 10,
                height: $(window).height() - 40
            }).datagrid('resize', {
                width: $(window).width() - 10,
                height: $(window).height() - 40
            });
        });

    });
</script>

<script type="text/javascript">
    // iframe 返回
    function frameReturnByClose() {
        $("#modalwindow").window('close');
    }

    // iframe 返回并刷新
    function frameReturnByReload(flag) {
        if (flag) {
            $("#List").datagrid('load');
        } else {
            $("#List").datagrid('reload');
        }
    }

    // 输出信息
    function frameReturnByMes(mes) {
        $.messageBox5s('提示', mes);
    }

    // 生成唯一Guid
    function GetGuid() {
        var s4 = function () {
            return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
        };
        return s4() + s4() + s4() + "-" + s4();
    }

    $(function () {
        $("#btnDetails").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {
                $("#modalwindow").html("<iframe width='100%' height='98%' scrolling='no' frameborder='0' src='/ManagerDetail/GetManagerDetail?managerDetailId=" + row.ManagerDetailId + "&Ieguid=" + GetGuid() + "'></iframe>");
                $("#modalwindow").window({ title: '详细', width: 500, height: 450, iconCls: 'icon-details' }).window('open');
            } else {
                $.messageBox5s('提示', '@Suggestion.PleseChooseToOperatingRecords');
            }
        });

        $("#btnQuery").click(function () {
            var queryStr = $('#txtQuery').val() + "/" + $('#CurrentRankStr').val() + "/" + $('#OldRankStr').val() + "/" + $('#ChannelRankChangeStr').val();
            $('#List').datagrid({ url: '/ManagerDetail/GetListByQuery?queryStr=' + encodeURI(queryStr) });
        });

        $("#btnDelete").click(function () {
            var row = $('#List').datagrid('getSelected');
            if (row != null) {
                $.messager.confirm('提示', '@Suggestion.YouWantToDeleteTheSelectedRecords', function (r) {
                    if (r) {
                        $.post("/ManagerDetail/DeleteManagerDetail?managerDetailId=" + row.ManagerDetailId, function (data) {
                            if (data==1) {
                                $('#List').datagrid('load');
                            }
                            $.messageBox5s('提示', '@Suggestion.DeleteSucceed');
                        }, "json");
                    }
                });
            } else {
                $.messageBox5s('提示', '@Suggestion.PleseChooseToOperatingRecords');
            }
        });
    });
</script>